id: P010645
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:17:59.113151
source_metadata:
  id: bdr:W1KG15517
  title: བཀའ་གདམས་ཀྱི་མན་ངག་བེའུ་བུམ་སྔོན་པོའི་རྩ་འགྲེལ།
  author: ''
  volumes:
    d47936080b0340428d31d32b66657268:
      image_group_id: I1KG15525
      title: ''
      volume_number: 1
      total_pages: 522
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
