id: IB89E9BAE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:46:35+00:00'
last_modified: '2022-06-08T16:28:32.485800+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15517
  title: བཀའ་གདམས་ཀྱི་མན་ངག་བེའུ་བུམ་སྔོན་པོའི་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6A3E:
      image_group_id: I1KG15525
      title: ''
      total_pages: 522
      order: 1
      base_file: 6A3E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
